# Generated by Django 3.0.5 on 2020-06-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name_or_bussiness', models.CharField(max_length=100)),
                ('Aadhar_Card', models.CharField(max_length=12)),
                ('Pan_Card', models.CharField(max_length=10, null=True)),
                ('Income', models.FloatField(blank=True, null=True)),
                ('pdf', models.FileField(upload_to='books/pdfs/')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
            ],
        ),
    ]
