# Generated by Django 3.0.5 on 2020-06-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('firstname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=150, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('age', models.CharField(max_length=3, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('city', models.CharField(max_length=200, null=True)),
                ('Zip', models.CharField(max_length=10, null=True)),
                ('State', models.CharField(max_length=200, null=True)),
                ('DOB', models.DateField()),
                ('Address', models.TextField()),
            ],
        ),
    ]
